language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - echo $TRAVIS_BRANCH
  - yarn install
  - yarn run build
  #- yarn run test
after_success:
  - codecov
