language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install
  - yarn run build
  #- yarn run test
after_success:
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(staging)$

