export const QUERY_MEASUREMENTS = 'QUERY_MEASUREMENTS';
export type QUERY_MEASUREMENTS = typeof QUERY_MEASUREMENTS;

export const MEASUREMENT_RESULTS = 'MEASUREMENT_RESULTS';
export type MEASUREMENT_RESULTS = typeof MEASUREMENT_RESULTS;

export const MEASUREMENT_FAIL = 'MEASUREMENT_FAIL';
export type MEASUREMENT_FAIL = typeof MEASUREMENT_FAIL;
